/* Typed runtime Tailwind variants selected by component state. */
export const dynamicTailwindRecipes: Readonly<Record<string, string>> = {
  "button--compact": "[min-height:34px] [padding:0.45rem_0.7rem] [font-size:0.82rem]",
  "button--default": "[min-height:42px] [padding:0.68rem_1rem]",
  "button--large": "[min-height:48px] [padding:0.82rem_1.15rem]",
  "button--primary": "[background:var(--brand-solid)] [border-color:var(--brand-solid)] [color:#fff] [box-shadow:0_1px_2px_rgb(12_42_62_/_0.16)] [&:hover:not(:disabled)]:[background:var(--brand-solid-hover)] [&:hover:not(:disabled)]:[border-color:var(--brand-solid-hover)] [&:active:not(:disabled)]:[background:var(--brand-solid-active)] [&:active:not(:disabled)]:[transform:translateY(1px)]",
  "button--secondary": "[background:var(--surface-elevated)] [border-color:var(--neutral-300)] [color:var(--neutral-800)] [box-shadow:0_1px_1px_rgb(15_23_42_/_0.03)] [&:hover:not(:disabled)]:[background:var(--neutral-50)] [&:hover:not(:disabled)]:[border-color:var(--neutral-400)]",
  "button--tertiary": "[background:transparent] [color:var(--kc-700)] [&:hover:not(:disabled)]:[background:var(--kc-50)] [&:hover:not(:disabled)]:[color:var(--kc-900)]",
  "button--danger": "[background:var(--danger-solid)] [color:#fff]",
  "app-tooltip--bottom": "[top:calc(100%_+_10px)] [left:50%] [transform:translate(-50%,_-4px)] after:[top:-5px] after:[left:calc(50%_-_4px)] after:[border-right:0] after:[border-bottom:0] after:[transform:rotate(45deg)] [.icon-button:hover_>_&]:[transform:translate(-50%,_0)] [.icon-button:focus-visible_>_&]:[transform:translate(-50%,_0)] [.evidence-item_.icon-button_>_&]:[right:0] [.evidence-item_.icon-button_>_&]:[left:auto] [.evidence-item_.icon-button_>_&]:[transform:translate(0,_-4px)] [.evidence-item_.icon-button_>_&::after]:[right:14px] [.evidence-item_.icon-button_>_&::after]:[left:auto] [.evidence-item_.icon-button:hover_>_&]:[transform:translate(0,_0)] [.evidence-item_.icon-button:focus-visible_>_&]:[transform:translate(0,_0)] max-[1100px]:[.mobile-shell-strip__actions_.icon-button_>_&]:[right:0] max-[1100px]:[.mobile-shell-strip__actions_.icon-button_>_&]:[left:auto] max-[1100px]:[.mobile-shell-strip__actions_.icon-button_>_&]:[transform:translate(0,_-4px)] max-[1100px]:[.mobile-shell-strip__actions_.icon-button_>_&::after]:[right:14px] max-[1100px]:[.mobile-shell-strip__actions_.icon-button_>_&::after]:[left:auto] max-[1100px]:[.mobile-shell-strip__actions_.icon-button:hover_>_&]:[transform:translate(0,_0)] max-[1100px]:[.mobile-shell-strip__actions_.icon-button:focus-visible_>_&]:[transform:translate(0,_0)] [.row-actions_&]:[left:auto] [.row-actions_&]:[right:0] [.row-actions_&]:[transform:translate(0,_-4px)] [.table-row-actions_&]:[left:auto] [.table-row-actions_&]:[right:0] [.table-row-actions_&]:[transform:translate(0,_-4px)] [.dialog__header_&]:[left:auto] [.dialog__header_&]:[right:0] [.dialog__header_&]:[transform:translate(0,_-4px)] [.row-actions_&::after]:[left:auto] [.row-actions_&::after]:[right:12px] [.table-row-actions_&::after]:[left:auto] [.table-row-actions_&::after]:[right:12px] [.dialog__header_&::after]:[left:auto] [.dialog__header_&::after]:[right:12px] [.row-actions_.icon-button:hover_>_&]:[transform:translate(0,_0)] [.row-actions_.icon-button:focus-visible_>_&]:[transform:translate(0,_0)] [.table-row-actions_.icon-button:hover_>_&]:[transform:translate(0,_0)] [.table-row-actions_.icon-button:focus-visible_>_&]:[transform:translate(0,_0)] [.dialog__header_.icon-button:hover_>_&]:[transform:translate(0,_0)] [.dialog__header_.icon-button:focus-visible_>_&]:[transform:translate(0,_0)]",
  "app-tooltip--top": "[bottom:calc(100%_+_10px)] [left:50%] [transform:translate(-50%,_4px)] after:[bottom:-5px] after:[left:calc(50%_-_4px)] after:[border-top:0] after:[border-left:0] after:[transform:rotate(45deg)] [.icon-button:hover_>_&]:[transform:translate(-50%,_0)] [.icon-button:focus-visible_>_&]:[transform:translate(-50%,_0)]",
  "app-tooltip--right": "[top:50%] [left:calc(100%_+_11px)] [transform:translate(4px,_-50%)] after:[top:calc(50%_-_4px)] after:[left:-5px] after:[border-top:0] after:[border-right:0] after:[transform:rotate(45deg)] [.icon-button:hover_>_&]:[transform:translate(0,_-50%)] [.icon-button:focus-visible_>_&]:[transform:translate(0,_-50%)] [.collapse-control:hover_>_&]:[transform:translate(0,_-50%)] [.collapse-control:focus-visible_>_&]:[transform:translate(0,_-50%)]",
  "app-tooltip--left": "[top:50%] [right:calc(100%_+_11px)] [transform:translate(-4px,_-50%)] after:[top:calc(50%_-_4px)] after:[right:-5px] after:[border-bottom:0] after:[border-left:0] after:[transform:rotate(45deg)] [.icon-button:hover_>_&]:[transform:translate(0,_-50%)] [.icon-button:focus-visible_>_&]:[transform:translate(0,_-50%)]",
  "status-badge--compact": "[min-height:27px] [padding:0.22rem_0.5rem] [font-size:0.72rem]",
  "status-badge--initial": "[border-color:var(--danger-border)]! [background:var(--danger-surface)] [color:var(--danger)]",
  "status-badge--emerging": "[border-color:var(--warning-border)]! [background:var(--warning-surface)] [color:var(--warning)]",
  "status-badge--performing": "[border-color:var(--success-border)]! [background:var(--success-surface)] [color:var(--success)]",
  "status-badge--not-assessed": "[border-color:var(--neutral-300)]! [background:var(--neutral-50)] [color:var(--neutral-600)]",
  "completion-badge--complete": "[border-color:var(--success-border)]! [background:var(--success-surface)] [color:var(--success)]",
  "completion-badge--in-progress": "[border-color:var(--kc-200)]! [background:var(--kc-50)] [color:var(--kc-800)]",
  "completion-badge--not-started": "[border-color:var(--neutral-300)]! [background:var(--neutral-50)] [color:var(--neutral-600)]",
  "progress-fill--success": "[background:var(--success)]",
  "progress-fill--warning": "[background:var(--warning)]",
  "save-status--saved": "[&_svg]:[color:var(--success)]",
  "save-status--saving": "[&_svg]:[color:var(--kc-600)]",
  "save-status--failed": "[color:var(--danger)] [&_svg]:[color:var(--danger)]",
  "inline-message--info": "[border-color:var(--kc-200)]! [background:var(--kc-50)]",
  "inline-message--success": "[border-color:var(--success-border)]! [background:var(--success-surface)]",
  "inline-message--warning": "[border-color:var(--warning-border)]! [background:var(--warning-surface)]",
  "inline-message--danger": "[border-color:var(--danger-border)]! [background:var(--danger-surface)]",
  "section-card__icon--initial": "[background:var(--danger-surface)] [color:var(--danger)]",
  "section-card__icon--emerging": "[background:var(--warning-surface)] [color:var(--warning)]",
  "section-card__icon--performing": "[background:var(--success-surface)] [color:var(--success)]",
  "response-chip--no": "[border-color:var(--danger-border)]! [background:var(--danger-surface)] [color:var(--danger)]!",
  "response-chip--partial": "[border-color:var(--warning-border)]! [background:var(--warning-surface)] [color:var(--warning)]!",
  "response-chip--yes": "[border-color:var(--success-border)]! [background:var(--success-surface)] [color:var(--success)]!",
  "response-chip--none": "[border-color:var(--neutral-300)]! [background:var(--neutral-100)] [color:var(--neutral-500)]!",
  "response-option--selected": "[.response-option--no&]:[border-color:var(--danger)] [.response-option--no&]:[background:var(--danger-surface)] [.response-option--no&]:[box-shadow:0_0_0_1px_var(--danger)] [.response-option--partial&]:[border-color:var(--warning)] [.response-option--partial&]:[background:var(--warning-surface)] [.response-option--partial&]:[box-shadow:0_0_0_1px_var(--warning)] [.response-option--yes&]:[border-color:var(--success)] [.response-option--yes&]:[background:var(--success-surface)] [.response-option--yes&]:[box-shadow:0_0_0_1px_var(--success)] [@media_(forced-colors:_active)]:[border:2px_solid_currentColor]",
  "evidence-item__icon--file": "[background:var(--danger-surface)] [color:var(--danger)]",
  "evidence-item__icon--link": "[background:var(--kc-50)] [color:var(--kc-700)]",
  "distribution-fill": "[display:block] [height:100%] [border-radius:inherit] [@media_(forced-colors:_active)]:[background:Highlight]",
  "distribution-fill--brand": "[background:var(--kc-600)]",
  "distribution-fill--success": "[background:var(--success)]",
  "distribution-fill--warning": "[background:var(--warning)]",
  "distribution-fill--danger": "[background:var(--danger)]",
  "distribution-fill--neutral": "[background:var(--neutral-400)]",
  "step-item--current": "[color:var(--kc-800)] [&_>_span]:[border-color:var(--kc-600)] [&_>_span]:[box-shadow:0_0_0_4px_var(--kc-100)]",
  "step-item--complete": "[color:var(--kc-800)] [&_>_span]:[border-color:var(--success)] [&_>_span]:[background:var(--success-solid)] [&_>_span]:[color:#fff] after:[background:var(--success)]",
  "save-status--attention": "[color:var(--danger)] [&_svg]:[color:var(--danger)]",
  "requirement-audit-change__kind--added": "[background:var(--success-surface)] [color:var(--success)]",
  "requirement-audit-change__kind--updated": "[background:var(--kc-50)] [color:var(--kc-800)]",
  "requirement-audit-change__kind--deleted": "[background:var(--danger-surface)] [color:var(--danger)]"
};
